### ISSUE TITLE
[BUG] AxEnvoys not working at all on 1.21.1 paper server

### ISSUE THREAD

**Issue by xojupiterxo** [Artillex-Studios/Issues#13]
### Description of the bug

when doing /envoy start default nothing happens. 

When deleting the blocks in /envoy editor default it gives this error
https://mclo.gs/JfZ734W

when doing /envoy flare default getting this error
https://mclo.gs/L9T4Igl

starting envoy doesnt spawn any crates 

### Expected behaviour

Start the envoy we created.

break the blocks and remove that spawn location from the world.

give me a flare to start an envoy when placed.

start and envoy when the command /envoy start default is issued

### Steps to reproduce

i have no idea what the issue truly is, but the plugin isnt working hardly at all, i can edit where envoys are and such but they dont spawn, the flare isnt working wont be given to player.

### Which plugin is this issue with?

axenvoys

### Versions

running Paper version 1.21.1-116-master@e7e1ab5 (2024-09-30T23:17:54Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

version 2.0.4 for axenvoys

**Comment by xojupiterxo** [comment]
bump

**Comment by AverageGithub** [comment]
Update to 2.0.5
