### ISSUE TITLE
[BUG] Item Flags aren't carrying over

### ISSUE THREAD

**Issue by BurningCoolDude** [Artillex-Studios/Issues#14]
### Description of the bug

The item in the picture is recreated lore with hide_attributes to hide default attributes. As you can see in the screenshot, something is clearly messed up.
![Screenshot 2024-10-12 161613](https://github.com/user-attachments/assets/51d06e33-9008-4011-afd7-ac56b6a7a82e)

### Expected behaviour

The bottom When in main hand lore should be hidden.

### Steps to reproduce

This was using EcoItems, I have created the item with hide_attributes & as you can see, it did not. It also added extra lore color.

### Which plugin is this issue with?

axauctions

### Versions

AxAuctions - 1.13.7

**Comment by BurningCoolDude** [comment]
It appears this is an issue with compatibility with Eco (still has to be solved by AxAuctions)

**Comment by BenceX100** [comment]
The plugin should be compatible now in the latest version

**Comment by burnplayz** [comment]
Thank you!
