### ISSUE TITLE
[BUG] Premium players without logs when logging off

### ISSUE THREAD

**Issue by codingsvcks** [Artillex-Studios/Issues#16]
### Description of the bug

You cannot see the logs of online mode players that are outside the server and only allows you to see them if you are inside the server, as if they had no backups saved. This does not happen with cracked players. No errors in console.

I am using nLogin authentication and its way of managing UUIDs in REAL, which automatically uses Mojang's UUIDs when a player is online-mode.

[https://i.postimg.cc/4480cxFj/javaw-HSOwwh6bz-A.png](https://i.postimg.cc/4480cxFj/javaw-HSOwwh6bz-A.png)

### Expected behaviour

Open the menu of all player backups

### Steps to reproduce

Try to run /axir view player with a player in online mode that is not on the server. All this on a network with an authentication plugin and with Mojang UUIDs enabled.

### Which plugin is this issue with?

axinventoryrestore

### Versions

UniverseSpigot version git-UniverseSpigot-"eabdb49" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: eabdb49 on ver/1.20.4-plus)
Universe-git-UniverseSpigot-"eabdb49" (MC: 1.20.4)

**Comment by BenceX100** [comment]
Hey, can you try the latest version? That might solve this

**Comment by codingsvcks** [comment]
Sorry for the delay, it worked, thx
