### ISSUE TITLE
[BUG] EcoItem lores are doubled

### ISSUE THREAD

**Issue by BurningCoolDude** [Artillex-Studios/Issues#22]
### Description of the bug

All my item's lores made through EcoItems are being doubled.
![image](https://github.com/user-attachments/assets/3743b0dc-b20c-420d-b3a6-29d9a8d73e90)

### Expected behaviour

There should not be &z lore etc

### Steps to reproduce

Create an item using EcoItems, put the item on Auction House.

### Which plugin is this issue with?

axauctions

### Versions

This server is running Leaf version 1.21.1-DEV-ver/1.21.1@dfcae93 (2024-10-12T16:17:29Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
* You are 21 version(s) behind
Download the new version at: https://github.com/Winds-Studio/Leaf
Previous: 1.21.1-DEV-e860fce (MC: 1.21.1)
# Leaf is a PAPER Derivative

AxAuctions 1.13.7

**Comment by BenceX100** [comment]
The plugin should be compatible now in the latest version
