### ISSUE TITLE
[BUG] AxAfkZone zone-per-ip-limit not working

### ISSUE THREAD

**Issue by lamlam098** [Artillex-Studios/Issues#25]
### Description of the bug

AxAfkZone zone-per-ip-limit not working

### Expected behaviour

123

### Steps to reproduce

tw

### Which plugin is this issue with?

axafkzone

### Versions

AxAfkZone version 1.2.0

**Comment by AverageGithub** [comment]
Hi, what do you exactly mean by "not working"? What isn't working? How is it not working?

**Comment by BenceX100** [comment]
Not enough information
