### ISSUE TITLE
[BUG] log spam

### ISSUE THREAD

**Issue by Crusfire63** [Artillex-Studios/Issues#34]
### Description of the bug

when i hover my mouse on a rank i have configured, i have log spam in console (not in chat minecraft or other)

`9cce6-a5da4f54a6-76415660f0-d527c7662b-87b56e7d4c-acf78e04d9-6ea8f3df90-a2fd14bb83-8093a93ffd-a20d9f83c0-1a78673380-7961b65891-e80d9e2d6e-bb0589577d-300c4895c2-0c7a66997d-70685`

### Expected behaviour

?

### Steps to reproduce

Just open rank and hover mouse

### Which plugin is this issue with?

axrankmenu

### Versions

AxRankMenu-1.8.0

**Comment by BenceX100** [comment]
Can you show what is exactly happening? Also if it is in your client's console, that is probably not caused by the plugin

**Comment by BenceX100** [comment]
Not caused by the plugin
