### ISSUE TITLE
[BUG] Sellwands Won't Sell

### ISSUE THREAD

**Issue by CosmicCreator639** [Artillex-Studios/Issues#42]
### Description of the bug

My issue is trying to sell a chest, it lets me click it to view the price I can sell everything for. But it just will not let me sell anything inside of it!

### Expected behaviour

I expect the sellwands to sell the items in the chest. I have set prices and everything worked perfect many times, but then randomly it just stopped working. I have deleted and re-added the plugin many times.

### Steps to reproduce

No idea how to reproduce this issue.

### Which plugin is this issue with?

axsellwands

### Versions

![image](https://github.com/user-attachments/assets/e687ebf2-13cb-4831-8eb9-6b716821aaf3)

**Comment by BenceX100** [comment]
It uses the same code for getting the prices for both the inspect and sell action, so this should never happen 🤔

**Comment by BenceX100** [comment]
Not enough information
