### ISSUE TITLE
[BUG] New AxAuctions 1.17.1 version fails to load.

### ISSUE THREAD

**Issue by ZevinRS** [Artillex-Studios/Issues#48]
### Description of the bug

On startup there is a warn (https://mclo.gs/gxawdOE). You cannot use any AxAuctions commands in game but the plugin does not appear red when you run /plugins. I was able to fix the issue by downgrading to AxAuctions 1.16.3.

### Expected behaviour

The plugin should load perfectly fine and I should be able to run commands such as /ah in game.

### Steps to reproduce

I have no idea why this is happening but here are my logs https://mclo.gs/gxawdOE
I'm also using an offline mode server because its on a network so i need that to use velocity.
I've tried using 1.17.1 AxAuctions on paper & purpur and it has the same issue on both so the server software does not seem to matter.

### Which plugin is this issue with?

axauctions

### Versions

1.17.1

**Comment by sluhtie** [comment]
Can confirm, same Issue here running Purpur 1.21.1 Latest
![image](https://github.com/user-attachments/assets/f4ec8cec-deba-4d0f-a6da-21f8cd5a1e57)

**Comment by AverageGithub** [comment]
Fixed in 1.17.2
